#!/usr/bin/env python3
"""
Generate config_secrets.h from config/secrets.yaml

This script reads the secrets YAML file and generates a C header file
that can be included in the firmware build.

Usage:
    python scripts/generate_config.py

The generated header will be placed in firmware/main/config_secrets.h
"""

import os
import sys
import yaml

# Paths relative to project root
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRETS_FILE = os.path.join(PROJECT_ROOT, "config", "secrets.yaml")
OUTPUT_FILE = os.path.join(PROJECT_ROOT, "firmware", "main", "config_secrets.h")


def main():
    # Check if secrets file exists
    if not os.path.exists(SECRETS_FILE):
        print(f"Error: Secrets file not found: {SECRETS_FILE}")
        print("Please create config/secrets.yaml from config/secrets.yaml.example")
        sys.exit(1)

    # Read secrets
    with open(SECRETS_FILE, "r") as f:
        secrets = yaml.safe_load(f)

    # Extract values with defaults
    wifi_ap_password = secrets.get("wifi_ap_password", "dolphin123")
    wifi_sta_ssid = secrets.get("wifi_sta_ssid", "")
    wifi_sta_password = secrets.get("wifi_sta_password", "")
    ota_password = secrets.get("ota_password", "tamagotchi")

    # Generate header content
    header_content = f'''/**
 * @file config_secrets.h
 * @brief Auto-generated secrets configuration
 *
 * DO NOT EDIT - This file is generated by scripts/generate_config.py
 * Edit config/secrets.yaml instead and run the script.
 */

#ifndef CONFIG_SECRETS_H
#define CONFIG_SECRETS_H

// WiFi Access Point configuration
#define CONFIG_WIFI_AP_SSID         "Tamagotchi"
#define CONFIG_WIFI_AP_PASSWORD     "{wifi_ap_password}"

// WiFi Station configuration (home network)
#define CONFIG_WIFI_STA_SSID        "{wifi_sta_ssid}"
#define CONFIG_WIFI_STA_PASSWORD    "{wifi_sta_password}"

// Check if STA credentials are configured
#define CONFIG_WIFI_STA_CONFIGURED  ({1 if wifi_sta_ssid else 0})

// OTA update configuration
#define CONFIG_OTA_PASSWORD         "{ota_password}"

#endif // CONFIG_SECRETS_H
'''

    # Write output file
    with open(OUTPUT_FILE, "w") as f:
        f.write(header_content)

    print(f"Generated: {OUTPUT_FILE}")
    print(f"  WiFi AP SSID: Tamagotchi")
    print(f"  WiFi AP Password: {'*' * len(wifi_ap_password)}")
    print(f"  WiFi STA SSID: {wifi_sta_ssid if wifi_sta_ssid else '(not configured)'}")
    print(f"  WiFi STA Password: {'*' * len(wifi_sta_password) if wifi_sta_password else '(not configured)'}")
    print(f"  OTA Password: {'*' * len(ota_password)}")


if __name__ == "__main__":
    main()
